# Generated by Django 3.2.16 on 2022-12-16 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favourites',
        ),
    ]
